# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 04:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('GR', 'Graduated'), ('CO', 'Continuing'), ('FL', 'Failed')], default='CO', max_length=2)),
                ('awarded_year', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2017)])),
                ('scholarship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholartracker.ScholarshipType')),
            ],
        ),
    ]
