# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 04:05
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scholartracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(default='TH', max_length=2),
        ),
    ]
