# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 04:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholartracker', '0002_student_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='special_emphasis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scholartracker.Division'),
            preserve_default=False,
        ),
    ]
