# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 04:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholartracker', '0003_auto_20171005_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='awarded_year',
            field=models.PositiveIntegerField(default=2017, help_text='Use the following format: YYYY', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2017)]),
        ),
    ]
