# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 04:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholartracker', '0004_auto_20171005_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex='\\d+')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
