# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 04:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholartracker', '0006_auto_20171005_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(choices=[('M', 'Mobile'), ('H', 'Home'), ('W', 'Work'), ('F', 'Fax')], default='CO', max_length=1)),
                ('number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex='\\d+')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholartracker.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='mobilephone',
            name='owner',
        ),
        migrations.DeleteModel(
            name='MobilePhone',
        ),
    ]
