# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholartracker', '0007_auto_20171005_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree_sought_bs',
            field=models.BooleanField(default=False, verbose_name='Bachelor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='degree_sought_dr',
            field=models.BooleanField(default=False, verbose_name='Doctoral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='degree_sought_ms',
            field=models.BooleanField(default=False, verbose_name='Master'),
            preserve_default=False,
        ),
    ]
