# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholartracker', '0009_auto_20171005_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='type_name',
            new_name='name',
        ),
    ]
